# Generated by Django 5.1.4 on 2025-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_business_number_profile_store_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_grade',
            field=models.CharField(choices=[('BRONZE', '브론즈'), ('SILVER', '실버'), ('GOLD', '골드'), ('PLATINUM', '플래티넘')], default='BRONZE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('BRONZE', '브론즈'), ('SILVER', '실버'), ('GOLD', '골드'), ('VIP', 'VIP')], default='BRONZE', max_length=20),
        ),
    ]
