# Generated by Django 5.1.4 on 2025-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_bio_remove_user_profile_image_and_more'),
        ('products', '0003_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to='products.product'),
        ),
    ]
